# Generated by Django 2.1.5 on 2019-04-03 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='medecin',
            name='sexe_medecin',
            field=models.BooleanField(default=0),
        ),
    ]
