# Generated by Django 2.1.5 on 2019-04-07 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20190407_2349'),
    ]

    operations = [
        migrations.AddField(
            model_name='medecin',
            name='date_de_naissance',
            field=models.DateField(blank=True, null=True),
        ),
    ]
