# Generated by Django 2.1.5 on 2019-04-03 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_medecin_sexe_medecin'),
    ]

    operations = [
        migrations.RenameField(
            model_name='medecin',
            old_name='email_medecin',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='medecin',
            old_name='prenom_medecin',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='medecin',
            old_name='nom_medecin',
            new_name='last_name',
        ),
        migrations.RenameField(
            model_name='medecin',
            old_name='sexe_medecin',
            new_name='sexe',
        ),
        migrations.RenameField(
            model_name='medecin',
            old_name='username_medecin',
            new_name='username',
        ),
    ]
