# Generated by Django 2.1.5 on 2019-04-09 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_medecin_date_de_naissance'),
    ]

    operations = [
        migrations.AddField(
            model_name='medecin',
            name='photo',
            field=models.ImageField(default='main/static/main/images/medecins/medecin_login.png', upload_to='main/static/main/images/medecins'),
        ),
        migrations.AlterField(
            model_name='medecin',
            name='csv_file',
            field=models.FileField(blank=True, null=True, upload_to='main/static/main/csv/medecins'),
        ),
    ]
