# Generated by Django 2.1.5 on 2019-04-03 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20190403_1322'),
    ]

    operations = [
        migrations.RenameField(
            model_name='medecin',
            old_name='first_name',
            new_name='firstName',
        ),
        migrations.RenameField(
            model_name='medecin',
            old_name='last_name',
            new_name='lastName',
        ),
    ]
