# Generated by Django 2.1.5 on 2019-04-10 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20190409_1720'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medecin',
            name='photo',
            field=models.ImageField(default='main/media/main/images/medecins/medecin_login.png', upload_to='main/media/main/images/medecins'),
        ),
    ]
