# Generated by Django 2.1.5 on 2019-04-03 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20190403_1517'),
    ]

    operations = [
        migrations.RenameField(
            model_name='medecin',
            old_name='lastName',
            new_name='nom',
        ),
        migrations.RenameField(
            model_name='medecin',
            old_name='firstName',
            new_name='prenom',
        ),
    ]
