# Generated by Django 2.1.5 on 2019-04-10 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20190410_0132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medecin',
            name='photo',
            field=models.ImageField(default='main/images/medecin_login.png', upload_to='main/images/'),
        ),
    ]
