# Generated by Django 2.1.5 on 2019-04-03 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20190403_1921'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medecin',
            name='sexe',
            field=models.BooleanField(blank=True, default=0, null=True),
        ),
    ]
