# Generated by Django 2.1.5 on 2019-04-11 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20190410_0319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medecin',
            name='photo',
            field=models.ImageField(default='main/static/main/images/medecin_login.png', upload_to=''),
        ),
    ]
