# Generated by Django 2.1.5 on 2019-04-11 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_auto_20190411_0241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medecin',
            name='photo',
            field=models.ImageField(default='main/static/main/images/medecin_login.png', upload_to='images/medecins'),
        ),
    ]
