# Generated by Django 2.1.5 on 2019-04-11 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_auto_20190411_0404'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medecin',
            name='photo',
            field=models.ImageField(default='images/medecin_login.png', upload_to='images/medecins'),
        ),
    ]
