# Generated by Django 2.1.5 on 2019-04-11 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_auto_20190411_1820'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medecin',
            name='csv_file',
            field=models.FileField(blank=True, null=True, upload_to='csv/medecins'),
        ),
    ]
