# Generated by Django 2.1.5 on 2019-04-11 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_auto_20190411_1840'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medecin',
            name='csv_file',
            field=models.FileField(blank=True, null=True, upload_to='Django/pcd/main/static/main/csv/medecins'),
        ),
    ]
