# Generated by Django 2.1.5 on 2019-04-11 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_auto_20190411_1843'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medecin',
            name='csv_file',
            field=models.FileField(blank=True, null=True, upload_to='main/csv'),
        ),
    ]
