# Generated by Django 2.1.5 on 2019-04-12 02:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_auto_20190411_1911'),
    ]

    operations = [
        migrations.CreateModel(
            name='FichierCsv',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('csv_file', models.FileField(blank=True, null=True, upload_to='csv/medecins')),
            ],
        ),
        migrations.RemoveField(
            model_name='medecin',
            name='csv_file',
        ),
        migrations.AddField(
            model_name='patient',
            name='photo',
            field=models.ImageField(default='images/medecin_login.png', upload_to='images/patients'),
        ),
        migrations.AddField(
            model_name='fichiercsv',
            name='medecin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Medecin'),
        ),
    ]
