# Generated by Django 2.1.5 on 2019-04-12 19:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_auto_20190412_0313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fichiercsv',
            name='medecin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='csv_files', to='main.Medecin'),
        ),
    ]
