# Generated by Django 2.1.5 on 2019-04-29 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0026_medecin_region'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='sexe',
        ),
        migrations.AddField(
            model_name='patient',
            name='date_de_naissance',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='genre',
            field=models.CharField(choices=[('HOMME', 'HOMME'), ('FEMME', 'FEMME')], default='HOMME', max_length=10),
        ),
        migrations.AddField(
            model_name='patient',
            name='region',
            field=models.CharField(choices=[('Tunis', 'Tunis'), ('Ariana', 'Ariana'), ('Mannouba', 'Mannouba'), ('Ben Arous', 'Ben Arous'), ('Bizerte', 'Bizerte'), ('Nabeul', 'Nabeul'), ('Zaghouan', 'Zaghouan'), ('Beja', 'Beja'), ('Jendouba', 'Jendouba'), ('Le Kef', 'Le Kef'), ('Siliana', 'Siliana'), ('Kairouan', 'Kairouan'), ('Sousse', 'Sousse'), ('Mahdia', 'Mahdia'), ('Monastir', 'Monastir'), ('Kasserine', 'Kasserine'), ('Sfax', 'Sfax'), ('Gabes', 'Gabes'), ('Kebili', 'Kebili'), ('Gafsa', 'Gafsa'), ('Sidi Bouzid', 'Sidi Bouzid'), ('Tozeur', 'Tozeur'), ('Medenine', 'Medenine'), ('Tataouin', 'Tataouin')], default='Tunis', max_length=20),
        ),
    ]
