# Generated by Django 2.1.5 on 2019-05-01 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0027_auto_20190429_1220'),
    ]

    operations = [
        migrations.AddField(
            model_name='medecin',
            name='first_connection',
            field=models.IntegerField(default=1),
        ),
    ]
