# Generated by Django 2.1.5 on 2019-05-01 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0028_medecin_first_connection'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medecin',
            name='first_connection',
            field=models.IntegerField(default=0),
        ),
    ]
