# Generated by Django 2.1.5 on 2019-05-13 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0031_consultation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultation',
            name='resultat',
            field=models.TextField(blank=True, max_length=2000, null=True),
        ),
    ]
