# Generated by Django 2.1.5 on 2019-05-13 13:44

from django.db import migrations, models
import django.db.models.deletion
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0002_auto_20150616_2121'),
        ('main', '0033_auto_20190513_1413'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaggedSymptoms',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='consultation',
            name='symptomes',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='main.TaggedSymptoms', to='taggit.Tag', verbose_name='Tags'),
        ),
        migrations.AddField(
            model_name='taggedsymptoms',
            name='content_object',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Consultation'),
        ),
        migrations.AddField(
            model_name='taggedsymptoms',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='main_taggedsymptoms_items', to='taggit.Tag'),
        ),
    ]
