# Generated by Django 2.1.5 on 2019-05-13 14:45

from django.db import migrations
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0002_auto_20150616_2121'),
        ('main', '0035_auto_20190513_1536'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consultation',
            name='symptomes',
        ),
        migrations.AddField(
            model_name='consultation',
            name='symptomes',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
